### PR TITLE
add a param for the server url

### PR DESCRIPTION
**Pull request by alikon**
changed from 
```
 'http://<your url>/submit'
```
to plugin param

### CODE REVIEW

**Comment by wilsonge** [comment]
This shouldn't be a parameter. The only reason it is one at the moment is because we don't have a permanent server location set up. Once we've set up a permanent location it will be hardcoded into the plugin

**Comment by mbabker** [comment]
I'd still make it a param that way it can be tested without feeding data to
the live server and not hacking the plugin.

**Comment by wilsonge** [comment]
Can you please alter the default param to be `http://developer.joomla.org/stats` please? And I'll get this merged

**Comment by alikon** [comment]
default param setted

**Pull request merged**
